version: '3'
services:
  angular:
    build:
      context: ./frontend
    ports:
      - "4200:4200"
  backend:
    build:
      context: ./backend
    volumes:
      - .:/src
    command: npm run start:dev # development server
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DEBUG: backend:*
    links:
      - mongodb
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    ports:
      - "127.0.0.1:27018:27017"
    environment:
      # change mongodb user and password as you wish
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=pass
    volumes:
    - './data:/data/db'
